spring:
  datasource:
    username: carb_calculator
    password: carb_calculator
    url: jdbc:mysql://192.168.0.114:3306/carb_calculator
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true